import { setupWorker } from "msw/browser";

import { handlers } from "./handlers";

/**
 * The Service Worker, for `npm run dev` with no backend running.
 *
 * `public/mockServiceWorker.js` is generated by `npx msw init public` and
 * committed: it has to be served from the site root, and without it the
 * worker has nothing to register.
 */
export const worker = setupWorker(...handlers);
