import { setupWorker } from "msw/browser";

import { handlers } from "./handlers";

// `public/mockServiceWorker.js` is committed and was generated by `npx msw init
// public`. It has to be served from the site root, which is why it lives in
// public/ rather than src/.
export const worker = setupWorker(...handlers);
